basePath: /api/v1
host: localhost:8080
info:
  contact:
    name: ITCFG Team
  description: 配置管理与部署自动化系统 API 文档
  title: ITCFG 配置中台 API
  version: "1.0"
paths: {}
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
